[config]

[templates.kitty]
input_path='~/dotfiles/.config/matugen/templates/dark/kitty.conf'
output_path='~/dotfiles/.config/kitty/themes/matugen.conf'
post_hook = 'kitty +kitten themes --reload-in=all matugen'

[templates.waybar]
input_path='~/dotfiles/.config/matugen/templates/dark/waybar.css'
output_path='~/dotfiles/.config/waybar/colors-matugen.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path='~/dotfiles/.config/matugen/templates/dark/rofi.rasi'
output_path='~/dotfiles/.config/rofi/colors-matugen.rasi'

[templates.swaync]
input_path='~/dotfiles/.config/matugen/templates/dark/swaync.css'
output_path='~/dotfiles/.config/swaync/colors-matugen.css'
post_hook = 'swaync-client --reload-css'

[templates.hyprland]
input_path='~/dotfiles/.config/matugen/templates/dark/hyprland.conf'
output_path='~/dotfiles/.config/hypr/themes/colors-matugen.conf'

[templates.btop]
input_path = '~/dotfiles/.config/matugen/templates/dark/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.gtk3]
input_path = '~/dotfiles/.config/matugen/templates/dark/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/dotfiles/.config/matugen/templates/dark/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/dotfiles/.config/matugen/templates/dark/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/dotfiles/.config/matugen/templates/dark/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.spotify]
input_path = '~/dotfiles/.config/matugen/templates/dark/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
#post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'

[templates.opencode]
input_path = '~/dotfiles/.config/matugen/templates/dark/opencode.json'
output_path = '~/.config/opencode/themes/matugen.json'
